export const ClassNames = {
    INPUT: 'input-wrapper',
    FILE_INPUT: 'file-input',
    // FILE_INPUT_WRAPPER: 'file-input-wrapper',
    INPUT_SPAN: 'input-span',
    INPUT_FILLED: 'input-filled',
    FILE_INPUT_BTNS: 'file-input-btns',
    FILE_INPUT_NAME: 'file-input-name',
    STANDARD_BTN: 'standard-btn',
    MODAL_WRAPPER: 'modal-wrapper',
    MODAL_CLOSE: 'modal-close',
    MODAL_CLOSE_BTN: 'modal-close-btn',
    MODAL_CONTENT: 'modal-content',
    MODAL_HEADER: 'modal-header',
    MODAL_BODY: 'modal-body',
    // menu
    NAV: 'nav',
    NAV_SECTION: 'nav-section',
    NAV_ITEM: 'nav-item',
    NAV_LOGO: 'nav-logo',
    NAV_UPDATES: 'nav-updates',
    NAV_ACCOUNT: 'nav-account-info',
    NAV_ACCOUNT_PIC: 'nav-account-pic-menu',
    NAV_SEARCH: 'nav-search',
    NOT_WRAPPER: 'notification-wrapper',
    // login
    LOGIN_PAGE: 'login-page',
    LOGIN_WRAPPER: 'login-wrapper',
    LOGIN_TYPING: 'typing',
    LOGIN_FORM: 'login-form',
    LOGIN_BTNS: 'login-buttons',
    LOGIN_BTN: 'login-btn',
    LOGIN_REGISTER_BTN: 'register-btn',
    // register
    REGISTER_WRAPPER: 'register-wrapper',
    REGISTER_FORM: 'register-form',
}